//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Configuracoes
    {
        public int CON_ID { get; set; }
    }

    class T_Configuracoes_ResultConfiguration : EntityTypeConfiguration<T_Configuracoes>
    {
        public T_Configuracoes_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.CON_ID);

            this.Property(c => c.CON_ID)
                .HasColumnName("CON_ID")
                .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_Configuracoes");
        }
    }
}
