//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Departamentos
    {
        public T_Departamentos()
        {
            this.T_Indicadores_Departamentos = new HashSet<T_Indicadores_Departamentos>();
        }
    
        public int DEP_ID { get; set; }
        public string DEP_NOME { get; set; }
    
        public virtual ICollection<T_Indicadores_Departamentos> T_Indicadores_Departamentos { get; set; }
    }

    class T_Departamentos_ResultConfiguration : EntityTypeConfiguration<T_Departamentos>
    {
        public T_Departamentos_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.DEP_ID);

            this.Property(c => c.DEP_ID)
                .HasColumnName("DEP_ID")
                .IsRequired();

            this.Property(c => c.DEP_NOME)
                .HasColumnName("DEP_NOME")
                .HasMaxLength(80)
                .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_Departamentos");
        }
    }
}
