//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Grupo_Indicador
    {
        public int GRU_IND_ID { get; set; }
        public int GRU_ID { get; set; }
        public int IND_ID { get; set; }
    
        public virtual T_Grupo T_Grupo { get; set; }
        public virtual T_Indicadores T_Indicadores { get; set; }
    }

    class T_Grupo_Indicador_ResultConfiguration : EntityTypeConfiguration<T_Grupo_Indicador>
    {
        public T_Grupo_Indicador_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.GRU_IND_ID);

            this.Property(c => c.GRU_IND_ID)
                .HasColumnName("GRU_IND_ID")
                .IsRequired();

            this.Property(c => c.GRU_ID)
                .HasColumnName("GRU_ID")
                .IsRequired();

            this.HasRequired(c => c.T_Grupo)
                .WithMany(c => c.T_Grupo_Indicador)
                .HasForeignKey(x => x.GRU_ID);

            this.Property(c => c.IND_ID)
                .HasColumnName("IND_ID")
                .IsRequired();

            this.HasRequired(c => c.T_Indicadores)
                .WithMany(c => c.T_Grupo_Indicador)
                .HasForeignKey(x => x.IND_ID);

            // Configurando a Tabela
            this.ToTable("T_Grupo_Indicador");
        }
    }
}
