//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity.ModelConfiguration;

    public class T_Grupo
    {
        public T_Grupo()
        {
            this.T_Grupo_Indicador = new HashSet<T_Grupo_Indicador>();
            this.T_USER_GRUPO = new HashSet<T_USER_GRUPO>();
        }
        [Required]
        public int GRU_ID { get; set; }
        [Required(ErrorMessage ="Prencimento Obrigatório.")]
        [MaxLength(80, ErrorMessage = "Permitido no máximo 80 caracteres.")]
        public string NOME { get; set; }
        [Required(ErrorMessage = "Prencimento Obrigatório.")]
        public int EXIBELISTA { get; set; }
        [Required(ErrorMessage = "Prencimento Obrigatório.")]
        [MaxLength(2000, ErrorMessage = "Permitido no máximo 2000 caracteres.")]
        public string GRU_DESCRICAO { get; set; }

        public virtual ICollection<T_Grupo_Indicador> T_Grupo_Indicador { get; set; }
        public virtual ICollection<T_USER_GRUPO> T_USER_GRUPO { get; set; }
    }

    class T_Grupo_ResultConfiguration : EntityTypeConfiguration<T_Grupo>
    {
        public T_Grupo_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.GRU_ID);

            this.Property(c => c.GRU_ID)
                .HasColumnName("GRU_ID")
                .IsRequired();

            this.Property(c => c.NOME)
                .HasColumnName("NOME")
                .HasMaxLength(80)
                .IsRequired();

            this.Property(c => c.EXIBELISTA)
                .HasColumnName("EXIBELISTA")
                .IsRequired();

            this.Property(c => c.GRU_DESCRICAO)
                .HasColumnName("GRU_DESCRICAO")
                .HasMaxLength(2000)
                .IsRequired();
                


            // Configurando a Tabela
            this.ToTable("T_Grupo");
        }
    }
}
