//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Informacoes_Complementares
    {
        public int INF_ID { get; set; }
        public string INF_DESCRICAO { get; set; }
        public decimal INF_VALOR { get; set; }
        public int MET_ID { get; set; }
        public string INF_DATA { get; set; }
    
        public virtual T_Metas T_Metas { get; set; }
    }

    class T_Informacoes_Complementares_ResultConfiguration : EntityTypeConfiguration<T_Informacoes_Complementares>
    {
        public T_Informacoes_Complementares_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.INF_ID);

            this.Property(c => c.INF_ID)
                .HasColumnName("INF_ID")
                .IsRequired();

            this.Property(c => c.INF_DESCRICAO)
                .HasMaxLength(100)
                .HasColumnName("INF_DESCRICAO")
                .IsRequired();

            this.Property(c => c.INF_VALOR)
                .HasColumnName("INF_VALOR")
                .HasPrecision(18,2)
                .IsRequired();

            this.Property(c => c.MET_ID)
                .HasColumnName("MET_ID")
                .IsRequired();

            this.HasRequired(c => c.T_Metas)
                .WithMany(c => c.T_Informacoes_Complementares)
                .HasForeignKey(x => x.MET_ID);

            this.Property(c => c.INF_DATA)
                .HasColumnName("INF_DATA")
                .HasMaxLength(8)
                .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_Informacoes_Complementares");
        }
    }
}
