//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_MESES
    {
        public string MES { get; set; }
        public int fator { get; set; }
    }

    class T_MESES_ResultConfiguration : EntityTypeConfiguration<T_MESES>
    {
        public T_MESES_ResultConfiguration()
        {
            this.HasKey(c => c.MES);

            this.Property(c => c.MES)
                .HasMaxLength(2)
                .HasColumnName("MES")
                .IsRequired();

            this.Property(c => c.fator)
                .HasColumnName("fator")
                .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_MESES");
        }
    }
}
