//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;

    public class T_Medicoes
    {
        public int MED_ID { get; set; }
        public System.DateTime MED_DATA { get; set; }
        public string MED_VALOR { get; set; }
        public Nullable<int> MET_ID { get; set; }
        public string MED_DATAMEDICAO { get; set; }
        public Nullable<decimal> MED_PONDERACAO { get; set; }
        public Nullable<int> UNI_ID { get; set; }
        public string MED_AC_ANO { get; set; }

        public virtual T_Unidade T_Unidade { get; set; }
        public virtual T_Metas T_Metas { get; set; }

        public int? DimId { get; set; }
        public string DimDescricao { get; set; }
        public string DimSubId { get; set; }
        public string DimSubDescricao { get; set; }
        public string FatId { get; set; }
        public string FatDescricao { get; set; }
        public string PerId { get; set; }
        public string PerDescricao { get; set; }
        public int  IndId{ get; set; }
    }

    class T_Medicoes_ResultConfiguration : EntityTypeConfiguration<T_Medicoes>
    {
        public T_Medicoes_ResultConfiguration()
        {
            ToTable("T_MEDICOES");
            // Configurando propriedades e chaves
            this.HasKey(c => c.MED_ID);

            this.Property(c => c.MED_ID)
                .HasColumnName("MED_ID")
                .IsRequired();

            this.Property(c => c.MED_DATA)
                .HasColumnName("MED_DATA")
                .IsRequired();

            this.Property(c => c.MED_VALOR)
                .HasMaxLength(50)
                .HasColumnName("MED_VALOR")
                .IsOptional();

            this.Property(c => c.MET_ID)
                .HasColumnName("MET_ID")
                .IsOptional();

            this.HasOptional(c => c.T_Metas)
                .WithMany(c => c.T_Medicoes)
                .HasForeignKey(c => c.MET_ID);

            this.Property(c => c.MED_DATAMEDICAO)
                .HasColumnName("MED_DATAMEDICAO")
                .HasMaxLength(8)
                .IsOptional();

            this.Property(c => c.MED_PONDERACAO)
                .HasColumnName("MED_PONDERACAO")
                .HasPrecision(18, 2)
                .IsOptional();

            this.Property(c => c.UNI_ID)
                .HasColumnName("UNI_ID")
                .IsOptional();

            this.HasOptional(c => c.T_Unidade)
                .WithMany(c => c.T_Medicoes)
                .HasForeignKey(c => c.UNI_ID);

            this.Property(c => c.MED_AC_ANO)
                .HasColumnName("MED_AC_ANO")
                .HasMaxLength(70)
                .IsOptional();

            this.Property(c => c.DimId)
               .HasColumnName("DIM_ID")
               .IsOptional();
            this.Property(c => c.DimDescricao)
               .HasColumnName("DIM_DESCRICAO")
               .HasMaxLength(100)
               .IsOptional();

            this.Property(c => c.DimSubId)
            .HasColumnName("DIM_SUBDIMENSAO_ID")
            .HasMaxLength(100)
            .IsOptional();

            this.Property(c => c.DimSubDescricao)
               .HasColumnName("DIM_SUB_DESCRICAO")
               .HasMaxLength(100)
               .IsOptional();
            


            this.Property(c => c.FatId)
               .HasColumnName("FAT_ID")
               .HasMaxLength(100)
               .IsOptional();
            this.Property(c => c.FatDescricao)
               .HasColumnName("FAT_DESCRICAO")
               .HasMaxLength(100)
               .IsOptional();
            this.Property(c => c.PerId)
               .HasColumnName("PER_ID")
               .HasMaxLength(100)
               .IsOptional();
            this.Property(c => c.PerDescricao)
              .HasColumnName("PER_DESCRICAO")
              .HasMaxLength(100)
              .IsOptional();

            this.Property(c => c.IndId)
               .HasColumnName("IND_ID")
               .IsOptional();
        }
    }
}
