//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Metas
    {
        public T_Metas()
        {
            this.T_Medicoes = new HashSet<T_Medicoes>();
            this.T_Informacoes_Complementares = new HashSet<T_Informacoes_Complementares>();
            this.T_PlanoAcao = new HashSet<T_PlanoAcao>();
        }

        public int MET_ID { get; set; }
        public string MET_DTINICIO { get; set; }
        public string MET_DTFIM { get; set; }
        public string MET_ALVO { get; set; }
        public int MET_TIPOALVO { get; set; }
        public int IND_ID { get; set; }
        public double? MET_RANGE01 { get; set; }
        public double? MET_RANGE02 { get; set; }
        public double? MET_RANGE03 { get; set; }
        public int? DIM_ID { get; set; }
        public string PER_ID { get; set; }
        public string FAT_ID { get; set; }
        
            
        public virtual T_Indicadores T_Indicadores { get; set; }
        public virtual ICollection<T_Medicoes> T_Medicoes { get; set; }
        public virtual ICollection<T_Informacoes_Complementares> T_Informacoes_Complementares { get; set; }
        public virtual ICollection<T_PlanoAcao> T_PlanoAcao { get; set; }
    }

    class T_Metas_ResultConfiguration : EntityTypeConfiguration<T_Metas>
    {
        public T_Metas_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.MET_ID);

            this.Property(c => c.MET_ID)
                .HasColumnName("MET_ID")
                .IsRequired();

            this.Property(c => c.MET_DTINICIO)
                .HasColumnName("MET_DTINICIO")
                .HasMaxLength(8)
                .IsRequired();

            this.Property(c => c.MET_DTFIM)
                .HasColumnName("MET_DTFIM")
                .HasMaxLength(8)
                .IsRequired();

            this.Property(c => c.MET_ALVO)
                .HasMaxLength(50)
                .HasColumnName("MET_ALVO")
                .IsRequired();

                this.Property(c => c.FAT_ID)
               .HasMaxLength(50)
               .HasColumnName("FAT_ID")
               .IsOptional();

            this.Property(c => c.MET_TIPOALVO)
                .HasColumnName("MET_TIPOALVO")
                .IsRequired();

            this.Property(c => c.DIM_ID)
                .HasColumnName("DIM_ID")
                .IsOptional();

            this.Property(c => c.PER_ID)
               .HasMaxLength(3)
               .HasColumnName("PER_ID")
               .IsOptional();



            this.Property(c => c.IND_ID)
                .HasColumnName("IND_ID")
                .IsRequired();
            
            this.Property(c => c.MET_RANGE01)
               .HasColumnName("MET_RANGE01")
               .IsOptional();

            this.Property(c => c.MET_RANGE02)
                .HasColumnName("MET_RANGE02")
                .IsOptional();
            this.Property(c => c.MET_RANGE03)
                .HasColumnName("MET_RANGE03")
                .IsOptional();

            this.HasRequired(c => c.T_Indicadores)
                .WithMany(c => c.T_Metas)
                .HasForeignKey(c => c.IND_ID);

            
            
            // Configurando a Tabela
            this.ToTable("T_Metas");
        }
    }
}
