//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Perfil
    {
        public T_Perfil()
        {
            this.T_Usuario = new HashSet<T_Usuario>();
        }
    
        public int PER_ID { get; set; }
        public string PER_NOME { get; set; }
    
        public virtual ICollection<T_Usuario> T_Usuario { get; set; }
    }

    class T_Perfil_ResultConfiguration : EntityTypeConfiguration<T_Perfil>
    {
        public T_Perfil_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.PER_ID);

            this.Property(c => c.PER_ID)
                .HasColumnName("PER_ID")
                .IsRequired();

            this.Property(c => c.PER_NOME)
                .HasColumnName("PER_NOME")
                .HasMaxLength(50)
                .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_Perfil");
        }
    }
}
