//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_Tabela
    {
        public int ID_TABELA { get; set; }
        public string CODIGO { get; set; }
        public string NOME { get; set; }
    }

    class T_Tabela_ResultConfiguration : EntityTypeConfiguration<T_Tabela>
    {
        public T_Tabela_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.ID_TABELA);

            this.Property(c => c.ID_TABELA)
                .HasColumnName("ID_TABELA")
                .IsRequired();

            this.Property(c => c.CODIGO)
                .HasColumnName("CODIGO")
                .HasMaxLength(15)
                .IsRequired();

            this.Property(c => c.NOME)
              .HasColumnName("NOME")
              .HasMaxLength(80)
              .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_Tabela");
        }
    }
}
