//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.ModelConfiguration;
    
    public class T_USER_GRUPO
    {
        public int GRPUSER_ID { get; set; }
        public int GRU_ID { get; set; }
        public int ID_USUARIO { get; set; }
    
        public virtual T_Grupo T_Grupo { get; set; }
        public virtual T_Usuario T_Usuario { get; set; }
    }

    class T_USER_GRUPO_ResultConfiguration : EntityTypeConfiguration<T_USER_GRUPO>
    {
        public T_USER_GRUPO_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.GRPUSER_ID);

            this.Property(c => c.GRPUSER_ID)
                .HasColumnName("GRPUSER_ID")
                .IsRequired();

            this.Property(c => c.GRU_ID)
                .HasColumnName("GRU_ID")
                .IsRequired();

            this.HasRequired(c => c.T_Grupo)
                .WithMany(c => c.T_USER_GRUPO)
                .HasForeignKey(c => c.GRU_ID);

            this.Property(c => c.ID_USUARIO)
                .HasColumnName("ID_USUARIO")
                .IsRequired();

            this.HasRequired(c => c.T_Usuario)
                .WithMany(c => c.T_USER_GRUPO)
                .HasForeignKey(c => c.ID_USUARIO);

            // Configurando a Tabela
            this.ToTable("T_USER_GRUPO");
        }
    }
}
