//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using SGI.Areas.PlugAndPlay.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity.ModelConfiguration;

    public class T_Usuario
    {
        public T_Usuario()
        {
            this.T_PlanoAcao = new HashSet<T_PlanoAcao>();
            this.T_UNIUSER = new HashSet<T_UNIUSER>();
            this.T_USER_GRUPO = new HashSet<T_USER_GRUPO>();
            this.Tr_CabViscao = new HashSet<Tr_CabViscao>();
            this.T_Auditoria = new HashSet<T_Auditoria>();
            this.T_Favoritos = new HashSet<T_Favoritos>();
            this.MovimentosEstoque = new HashSet<MovimentoEstoque>();
            this.TargetsProduto = new HashSet<TargetProduto>();
        }

        public int ID_USUARIO { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
        [Required]
        public int ID_PERFIL { get; set; }
        public String ID_TURMA { get; set; }
        public int ATIVO { get; set; }

        public string CODERP { get; set; }

        public virtual Turma T_Turma { get; set; }
        public virtual T_Perfil T_Perfil { get; set; }
        public virtual ICollection<T_Auditoria> T_Auditoria { get; set; }
        public virtual ICollection<T_PlanoAcao> T_PlanoAcao { get; set; }
        public virtual ICollection<T_UNIUSER> T_UNIUSER { get; set; }
        public virtual ICollection<T_USER_GRUPO> T_USER_GRUPO { get; set; }
        public virtual ICollection<Tr_CabViscao> Tr_CabViscao { get; set; }
        public virtual ICollection<T_Favoritos> T_Favoritos { get; set; }
        public virtual ICollection<Feedback> T_Feedbacks { get; set; }
        public virtual ICollection<MovimentoEstoque> MovimentosEstoque { get; set; }
        public virtual ICollection<TargetProduto> TargetsProduto { get; set; }

    }

    class T_Usuario_ResultConfiguration : EntityTypeConfiguration<T_Usuario>
    {
        public T_Usuario_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.ID_USUARIO);

            this.Property(c => c.ID_USUARIO)
                .HasColumnName("ID_USUARIO")
                .IsRequired();

            this.Property(c => c.NOME)
                .HasColumnName("NOME")
                .HasMaxLength(80)
                .IsRequired();

            this.Property(c => c.EMAIL)
                .HasColumnName("EMAIL")
                .HasMaxLength(100)
                .IsRequired();

            this.Property(c => c.SENHA)
                .HasColumnName("SENHA")
                .HasMaxLength(50)
                .IsRequired();

            this.Property(c => c.ID_PERFIL)
                .HasColumnName("ID_PERFIL");

            this.Property(c => c.ID_TURMA)
               .HasColumnName("ID_TURMA").IsOptional();

            this.HasRequired(e => e.T_Perfil)
                .WithMany(t => t.T_Usuario)
                .HasForeignKey(c => c.ID_PERFIL);

            this.HasOptional(e => e.T_Turma)
                .WithMany(t => t.Usuarios)
                .HasForeignKey(c => c.ID_TURMA);

            this.Property(c => c.ATIVO)
                .HasColumnName("ATIVO")
                .IsRequired();

            this.Property(c => c.CODERP)
                .HasColumnName("CODERP")
                .HasMaxLength(200)
                .IsOptional();

            // Configurando a Tabela
            this.ToTable("T_Usuario");
        }
    }
}
