//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.ModelConfiguration;
    
    public class vw_SGI_PARAMETRO_RELMEDICOES
    {
        public vw_SGI_PARAMETRO_RELMEDICOES()
        {
            Dimensoes = new HashSet<Dimensao>();
        }
        public DateTime MED_DATA { get; set; }
        public Nullable<int> MET_ID { get; set; }
        public Nullable<int> NEG_ID { get; set; }
        public int IND_ID { get; set; }
        public Nullable<int> UNID { get; set; }
        public string UN { get; set; }
        public string IND_DESCRICAO { get; set; }
        public string Mes { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> META { get; set; }
        public double ValorAc { get; set; }
        public Nullable<double> METAMES { get; set; }
        public Nullable<double> METACU { get; set; }
        public double MED_PONDERACAO { get; set; }
        public int? DimId { get; set; }
        public string DimDescricao { get; set; }
        public string DimSubId { get; set; }
        public string DimSubDescricao { get; set; }
        public string FatId { get; set; }
        public string FatDescricao { get; set; }
        public string PerId { get; set; }
        public string PerDescricao { get; set; }
        public int MedId { get; set; }
     

        [NotMapped]
        public virtual ICollection<Dimensao>Dimensoes { get; set; }
    }
    class vw_SGI_PARAMETRO_RELMEDICOES_ResultConfiguration : EntityTypeConfiguration<vw_SGI_PARAMETRO_RELMEDICOES>
    {
        public vw_SGI_PARAMETRO_RELMEDICOES_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.MedId);
            // Configurando a Tabela
            this.ToTable("vw_SGI_PARAMETRO_RELMEDICOES");
        }
    }
}
